### ISSUE TITLE
Сделай для массивов любой длины

### ISSUE THREAD

**Issue by AnPogrebnyak** [OleksandrMerezhko/HomeWork#9]
https://github.com/OleksandrMerezhko/HomeWork/blob/bbb88092c7ab8be7fa5b005a85b17ec38907390c/L8_Massive4_1.java#L5

**Comment by OleksandrMerezhko** [comment]
по принципу варианта в L8_Massive4.java https://github.com/OleksandrMerezhko/HomeWork/blob/master/L8_Massive4.java  это был простой вариант, если бы мы не знали циклов :)
